### ISSUE TITLE
[BUG] Connection close is closing but handle not ending?

### ISSUE THREAD

**Issue by worksofliam** [markdirish/node-odbc#133]
![image](https://user-images.githubusercontent.com/3708366/96254111-a8758e00-0fac-11eb-8bfe-048f9f2c6409.png)

I am using jest to run unit tests in my app but on the teardown, I am closing all the connections in my pool (custom implementation) but jest is telling the handle isn't ending.

Any ideas?

Thanks!

**Comment by worksofliam** [comment]
So this works fine.

```
odbc.connect(config.db.connectionString).then((connection) => {
    console.log('open');
    connection.close().then(() => {
        console.log('closed');
    });
})
```

But this does not.

```    
    for (var i = 0; i < length; i++) {
      connection = this.pool.pop();
      await connection.close();
    }
```

Seems to be leaving handles open?

![image](https://user-images.githubusercontent.com/3708366/96256502-b3322200-0fb0-11eb-82e4-b375ab4e61bb.png)

**Comment by markdirish** [comment]
When a connection is added to a pool, its `close` is overwritten so that closing it returns it to a pool. Of course your custom implementation probably is not reusing any connections (or maybe it is?), so they should be closed anyways. You might see if the `fix-pooling` branch fixes the issues, it should now reuse connections by default.

But yeah, seems like _some_ issue with overriding the close method for connections in pools.

**Comment by markdirish** [comment]
Ok, pooling was changed a lot in the last few years, and @worksofliam hasn't harassed me about this for a while, so closing!
