### ISSUE TITLE
[QUESTION] Equivalent of GET DIAGNOSTICS :NbrOfRows = DB2_NUMBER_ROWS

### ISSUE THREAD

**Issue by MrTeapot** [markdirish/node-odbc#146]
Hey!

A common use case when writing web services is to offer filtered and paginated lists of records.
Pagination requires a couple of things:
* A limit (Using LIMIT in the SQL)
* An offset (Using OFFSET in the SQL)
* A count of retrieved records (Available in the .length property of the result array)
* A count of total number of records available - how can I retrieve this? is it possible without writing a separate SQL query with COUNT(*)? 
In embedded sql/rpgle we have DB2_NUMBER_ROWS. Can this be achieved using ODBC?

**Comment by markdirish** [comment]
I don't believe so. I think you best bet is using `COUNT(*)`

I remember reading a while ago about this, since it is a very helpful case, but I don't believe that there is an ODBC way to get the total number of records available from a statement before actually fetching them. This package currently just calls `SQLFetch` until there are no more rows to return, so you have to limit it using SQL like LIMIT and OFFSET. There is a `SQLRowCount` function, but this only returns the number of rows affected on UPDATE/INSERT/DELETE (and passed to you in the Result object as `count`).

There are some DBMS that _do_ allow you to get this information, but that is because they buffer all of the rows.

I think this is related to the effort to get cursors and `SQLFetchScroll` working in the package. Using that (future functionality), you could indicate that you want to fetch rows X at a time (similar to limit), and can just keep calling `next` or whatever function name to get the next X rows. You can also position the cursor where you want it, similar to OFFSET. But again, this won't tell you the _total_ number of records available. That is something I will be working heavily on in the next few weeks!
