### ISSUE TITLE
[BUG] Only 4 queries can execute in parallel?

### ISSUE THREAD

**Issue by trevan** [markdirish/node-odbc#169]
**Describe your system**
* `odbc` Package Version: 2.3.5
* ODBC Driver: unixodbc
* Database Name: Vertica
* Database Version: 9.3
* Database OS: CentOS
* Node.js Version: 10.16.2
* Node.js OS: Ubuntu

**Describe the bug**
The query to the database is inside of `QueryAsyncWorker` which is a child of `Napi::AsyncWorker`.  The code in `QueryAsyncWorker::Execute` is run in a worker thread.  By default, there are only 4 worker threads in a nodejs instance (this can be changed by modifying the UV_THREADPOOL_SIZE env variable).

Because of that, if you execute 4 slow queries, all the other queries will queue up behind those 4 queries.

**Expected behavior**
When running a query, most of the IO, cpu, memory is being done by the database (at least with Vertica).  The nodejs process is just waiting on the query to finish.  I would expect the other queries to be able to run in parallel instead of waiting for the 4 slow queries to finish.

**To Reproduce**
1. Ensure UV_THREADPOOL_SIZE isn't set
2. Create 5 connections
3. Execute 4 slow queries (>1 minute)
4. After 30 seconds, execute a fast query
5. The database won't even see the fast query until one of the slow queries finishes.

**Additional context**

**Comment by markdirish** [comment]
Definitely seems like less-than-ideal behavior, but are you aware of a work around (other than setting `UV_THREADPOOL_SIZE`)?

I'm not sure that trying to do something like.. call the `uv` library directly would be feasible. Also, many of the AsyncWorker classes do a lot of work in addition to calling queries. Pretty much every call to the driver is made in an AsyncWorker, and so all of that would need to be stitched together...

I think this package uses the prescribed method of firing off asynchronous work, but I agree that it is unfortunate that that most of the work is being sent off to the database while the threads sit there and wait.

**Comment by kadler** [comment]
ODBC does support [async execution](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/asynchronous-execution-polling-method?view=sql-server-ver15), but that would require quite a bit of work to support and not all drivers support async execution in the first place.

**Comment by markdirish** [comment]
I think that the N-API (and node-addon-api) layer would still be blocking, as 4 AsyncWorkers would be consumed and waiting for responses. Any other calls that came in would be waiting on a worker thread to free up. And from looking at the examples and reading the API documentation, I'm not sure there's a good way to have an AsyncWorker hand off the work to ODBC, free up its thread, then at a later time pick up the work that was returned from ODBC and continue processing/returning into the JavaScript environment.

**Comment by kadler** [comment]
The basics would be:

- node-odbc submits work to be done on a worker
- the worker calls ODBC and returns back the result
- node-odbc code receives the result and if the return code is SQL_STILL_EXECUTING, it queues up another worker action to poll the handle
- this polling continues until a result is returned or timeout or whatever

You'd basically have to wrap every ODBC API call.

Also, I don't think you could use the "notification method" for async ODBC, since we must unwind the worker stack and relinquish to the job pool, so you can't really have a notification callback come in asynchronously.

**Comment by markdirish** [comment]
This one has been open for a while, but I just don't see a feasible way to tackle it within the context of this package. Unless someone knows how other database connectors handle this (without doing the type of work-around @kadler has sketched-out), I'd be happy to investigate. Otherwise, the best solution would be to just utilize `UV_THREADPOOL_SIZE `, even if that is creating idle threads while the database does its thing.
