### ISSUE TITLE
Move to IBM github presence?

### ISSUE THREAD

**Issue by ThePrez** [markdirish/node-odbc#17]
I propose we move this to http://github.com/IBM/node-odbc

**Comment by markdirish** [comment]
One of the requests that wankdanker had when I took it over was that we didn't move it under the IBM organization GitHub, as it might turn off those who don't use IBM products or are connecting from non-IBM systems and/or to non-IBM databases.

Now, the actual code ownership doesn't change if it moves over there, since my work is all property of IBM, but hosting it in more "neutral" territory was the initial hope. Willing to keep entertain the idea, but I just want to make sure people will still be willing to contribute and test if it moves to the organization GitHub

**Comment by ThePrez** [comment]
That's a reasonable argument for keeping this in a more neutral territory. Closing this issue
