### ISSUE TITLE
[BUG] Query results returning cut off values at 63 bytes

### ISSUE THREAD

**Issue by bencmbrook** [markdirish/node-odbc#175]
**Describe your system**
* `odbc` Package Version: 2.3.6
* ODBC Driver: AmazonRedshiftODBC-64-bit-1.4.20.1001-1.x86_64.deb ([doc link](https://docs.aws.amazon.com/redshift/latest/mgmt/configure-odbc-connection.html))
* Database Name: Amazon Redshift
* Database Version: Amazon Redshift 1.0.24421
* Database OS: N/A
* Node.js Version: node:latest (15.12.0)
* Node.js OS: Docker image node:latest (Debian Stretch)

**Describe the bug**
When querying a table (in this case `SELECT schemaname, tablename FROM pg_catalog.pg_tables`), the returned values get cut off at 63 characters. When I inspect the `column` property from the result, I see `columnSize: 63`, however, this does not appear to be the case with the underlying table. When I look at the table in a SQL client (e.g. Postico), the full values are present in the table, and the columns do not show size constraints.

**Expected behavior**
I would receive the full 64+ char string value in the results.

**To Reproduce**
In a PostgreSQL-flavored DB (e.g. Redshift), create a table with a name that is >63 chars, then `SELECT schemaname, tablename FROM pg_catalog.pg_tables` using `connection.query()` to view the cut-off result.

**Code**
If applicable, add snippets of code to show:

* The offending code:
* Any DEBUG information printed to the terminal:
* Any error information returned from a function call:

**Additional context**

**Query:**
`connection.query('SELECT schemaname, tablename FROM pg_catalog.pg_tables')`

**Rows:**

```json
  {
    "schemaname": "example",
    "tablename": "this_is_fine"
  },
  {
    "schemaname": "example",
    "tablename": "this_table_is_an_example_of_something_that_gets_cut_off_too_ear"
  },
```

**Column metadata:**

```js
columns: [
  {
    name: 'schemaname',
    dataType: -9,
    columnSize: 63,
    decimalDigits: 0,
    nullable: true
  },
  {
    name: 'tablename',
    dataType: -9,
    columnSize: 63,
    decimalDigits: 0,
    nullable: true
  }
]
```

Could this be coming from node-odbc, or might this be an issue with the underlying driver? Or with ODBC itself?

**Comment by markdirish** [comment]
Let's see if we can unravel this mystery.

For an SQL_CHAR field, the `columnSize` that is returned in the column definitions in JavaScript equals the value returned from `SQLDescribeCol`.

```
{
  name: 'tablename',
  dataType: -9,
  columnSize: 63, // <--- This is what the Redshift ODBC driver describes the column size as
  decimalDigits: 0,
  nullable: true
}
```
The actual underlying buffer used to return data to is ColumnSize * 4 (the maximum number of bytes to represent a code-point in UTF-8) + 1 for the null terminator. So your buffer should actually have a size of 253. This is the amount of space that this package tells the driver is available to return data to, so if anything it should cutoff at 252 bytes. There's no reason that this package would be artificially cutting off at 63. It _sounds_ like the driver's doing.

I'm not sure what `dataType: -9` represents, it doesn't seem to be a "standard" ODBC type, but that's fine because driver's like to implement their own data types. It should default to binding to `SQL_CHAR`, and use the logic outlined above. Looking at [the Redshift documentation for these views](https://docs.aws.amazon.com/redshift/latest/dg/c_join_PG.html), it links to the [PostgreSQL documentation for the `pg_tables` view](https://www.postgresql.org/docs/12/view-pg-tables.html). Both of these have a datatype of `name`. Looking at [the documentation for character data types](https://www.postgresql.org/docs/current/datatype-character.html), it reads:

> The name type exists only for the storage of identifiers in the internal system catalogs and is not intended for use by the general user. Its length is currently defined as 64 bytes (63 usable characters plus terminator)

So it seems that the driver _and_ this package are returning the information as I would expect a PostgreSQL database to return it. Now, you are using Amazon Redshift. I am not 100% about the relationship between the two, but it looks like Redshift is based on PostgreSQL 8.0. Its possible that in Redshift proper the table names are stored OK, but when going through some "PostgreSQL layer" they are artificially limited by the "name" data type. Perhaps a cast would work?

`SELECT schemaname, CAST(tablename AS text) FROM pg_catalog.pg_tables`

Run that and post what gets returned, I'm interested if the cast will get it behave.

**Comment by kadler** [comment]
@mirish From the doc you linked to:

> The length is set at compile time (and is therefore adjustable for special uses)

Also from https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

>  The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

Possibly Amazon has changed this length on the server but not the driver?

**Comment by kadler** [comment]
Looks like they've changed it to 128 on the server: https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html

> The maximum length for the table name is 127 bytes; longer names are truncated to 127 bytes.

This seems like a bug in the RedShift ODBC driver.

@bencmbrook Are the results truncated when queried from `isql` as well? That would definitely point to this being a driver issue, not a node-odbc issue.

**Comment by bencmbrook** [comment]
Thank you so much for the thorough responses @markdirish and @kadler. I believe you're correct that this is a Redshift ODBC driver issue. I haven't had a moment to test this in `isql` yet, but I'm going to close this issue in the meantime. I'll also report back here once this is confirmed.

This package is great; thank you for maintaining it!

**Comment by bencmbrook** [comment]
> `SELECT schemaname, CAST(tablename AS text) FROM pg_catalog.pg_tables`
>
> Run that and post what gets returned, I'm interested if the cast will get it behave.

@markdirish this retrieves the complete table names!

**Comment by bencmbrook** [comment]
Filed this with Amazon here https://forums.aws.amazon.com/thread.jspa?messageID=982413&#982413
