### ISSUE TITLE
New feature request: Connection pool

### ISSUE THREAD

**Issue by ThePrez** [markdirish/node-odbc#18]
Proposing a connection pool class be written, similar (or identical to) the DBPool class of the [idb-pconnector](https://www.npmjs.com/package/idb-pconnector)

**Comment by markdirish** [comment]
Package has a connection pool class: https://github.com/markdirish/node-odbc#Pool

What features were you looking for? I think this one performs a little better, because it exposes a .query method, which allows you to fire off a query on any connection (if you just want to do a simple one-off query). If you want to do prepare/bind/execute workflow or multiple queries on the same connection, you can also explicitly checkout a connection from the pool.

**Comment by ThePrez** [comment]
Wow, not sure how I missed that! 
I was looking for a convenience method to group the prepare, bind, execute, and relinquish into one convenience method. `query()` might do that:
https://github.com/markdirish/node-odbc#querysql-parameters-callback-1

But can `query()` do UPDATES, DELETES, and procedure calls?

**Comment by markdirish** [comment]
Query() can do everything (and can even handle procedure calls), but to get an even _easier_ procedure call, I would do:

```
const connection = await pool.connect();
const result = await connection.callProcedure(null, "SCHEMA", "procName", parameters);
```

This .callProcedure method uses the "ODBC way" of call procedures.
