### ISSUE TITLE
[Q] connectionTimeout definition?

### ISSUE THREAD

**Issue by hellower** [markdirish/node-odbc#208]
Parameters:
.....
**connectionTimeout: How long before an idle connection will close, in seconds**
I think the meaning of above connectionTimeout is the meaning of idletimout below, is that correct?

If this is correct, how about renaming it to "idleTimeout" ?
I'm sorry if I was rude.
sorry for poor english.

--------------------------------------------------------------------
https://node-postgres.com/api/pool
  // number of milliseconds to wait before timing out when connecting a new client
  // by default this is 0 which means no timeout
  **connectionTimeout**Millis?: int,

  // number of milliseconds a client must sit idle in the pool and not be checked out
  // before it is disconnected from the backend and discarded
  // default is 10000 (10 seconds) - set to 0 to disable auto-disconnection of idle clients
  **idleTimeout**Millis?: int,

**Comment by markdirish** [comment]
Not rude at all! The link you posted is for Postgres, which seems to have slightly different terminology than the ODBC specification. The ODBC connection attributes can be found [on this page of the documentation](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function?view=sql-server-ver15). In ODBC, a connection timeout is:

> ...the number of seconds to wait for any request on the connection to complete before returning to the application. The driver should return SQLSTATE HYT00 (Timeout expired) anytime that it is possible to time out in a situation not associated with query execution or login.

Which sounds different from Postgres' `idleTimeout`, since it deals with actual requests and not idle timeouts. Postgres' `connectionTimeout` sounds similar to ODBC's login timeout:

> the number of seconds to wait for a login request to complete before returning to the application. The default is driver-dependent. If ValuePtr is 0, the timeout is disabled and a connection attempt will wait indefinitely.

Since this an ODBC package, I think it makes most sense to retain the ODBC terminology, even if individual database systems diverge from that terminology.

**Comment by markdirish** [comment]
Immediately after I closed it, I saw the issue. Our documentation is wrong and doesn't describe the connection timeout correctly:

```
connectionTimeout: How long before an idle connection will close, in seconds
```
should instead read something like
```
connectionTimeout: The number of seconds to wait for a request on the connection to complete before returning to the application
```

I will update the README to reflect this.

**Comment by hellower** [comment]
Thanks!!

**Comment by hellower** [comment]
Thanks!
