### ISSUE TITLE
Installing node-odbc leaves a massive 15MB "tmp" directory inside the package directory

### ISSUE THREAD

**Issue by ericmorand** [markdirish/node-odbc#237]
After installting node-odbc using `npm i odbc`, the directory `node_modules/odbc` contains a directory named `build-tmp-napi-v6` that weights around15MB. Removing this directory doesn't have any side effect, at least based on my testings and as it name seems to imply, it looks like a remainder of the node-gyp build execution.

15MB is massive, especially for micro-services.

**Comment by markdirish** [comment]
Certainly not something we want. Those are the build artifacts from the installation step, where it has to compile the C++ code to build the addon (when not downloading pre-built binaries). What operating system are you running? Just checked on my local install that I use for development, and sure enough I have the same directory, but it is 12M instead of 15M (still too big, of course). The actual artifact that it builds should be somewhere like `lib/bindings/napi-v6/odbc.node`, and for me is 2 MB.

I will take a look at it and try to get the build to clean up after itself.

**Comment by ericmorand** [comment]
I'm building from a Ubuntu box which may explain the difference of size.

The artifact weights around 3MB which is fine and expected in my opinion.

Note that executing the command `node-pre-gyp install --build-from-source` inside `node_modules/odbc` rebuild the artifact and also recreate this `build-tmp-napi-v6`.

Interestingly enough, installing sqlite3 and executing the same command as above into `node_modules/sqlite3` leads to a crash because I don't have python installed, but more importantly leaves a `build-tmp-napi-v3` around, not nearly as big (35KB) but still there. Is this an issue with `node-pre-gyp` that doesn't clean properly its temporary folder?

That said, I've added a "postinstall" script to my project that remove that directory, so the workaround is trivial. :)
