### ISSUE TITLE
SQLDescribeParam not implemented in FreeTds Driver

### ISSUE THREAD

**Issue by AlessioQ** [markdirish/node-odbc#250]
Hi,

I'm currently using odbc@1.4.6 in a production system.
My database is **Sybase 12.5** and odbc driver is **FreeTDS** 0.95.

I'm trying to migrate to odbc@2.4, but I have a problem with the function **SQLDescribeParam that is not implemented** in Freetds.
Due to that, I cannot execute .query method passing parameters..

I was wondering, why this issue is only in the new 2.X.X version of odbc (in which way old odbc version did use params?).
Any way to use parameterized query using freetds in odbc@2.x.x?

Thanks for any suggest or information.

This is my odbc debug log:
```
...
read$"          24d4-ec0	EXIT  SQLDescribeParam  with return code -1 (SQL_ERROR)
		HSTMT               0x00000000003390F0
		UWORD                        1 
		SWORD *             0x0000000003F406F4
		SQLULEN *           0x0000000003F406F8
		SWORD *             0x0000000003F40700
		SWORD *             0x0000000003F40720

		DIAG [IM001] [Microsoft][Driver Manager ODBC] Il driver non supporta questa funzione (0) 
```
...

**Comment by markdirish** [comment]
It looks like the old 1.x version of the odbc package simply looked at what type of variable you passed in, and then did its best guess to what the types it should bind are: https://github.com/wankdanker/node-odbc/blob/v1/src/odbc.cpp#L654-L755

It looks like a few years ago, an issue was opened on the driver to implement the function: https://github.com/FreeTDS/freetds/issues/104

The odbc connector they are talking about appears to have created a special function to describe parameters explicitly, but I don't think the same would be possible here since it requires programming for a specific database's syntax (which is sort of antithetical to the whole point of ODBC).

I'm not _against_ creating a code path similar to 1.x, and have a QueryOption like.. `useSQLDescribeParam` that defaults to `true`. 95%+ of users would never have to touch/know about the option, but for users using FreeTDS they could tell it to skip `SQLDescribeParam` and just best guess.

It isn't super high on priority, but I will keep it in mind and look into it soon.

**Comment by markdirish** [comment]
Of course, the best solution would be if FreeTDS implemented the function...

**Comment by AlessioQ** [comment]
I'll try to keep open this issue due to this answer:

https://github.com/markdirish/node-odbc/issues/250#issuecomment-1100113736

Thanks,
Alessio

**Comment by schimmelc** [comment]
Has there been a fix for this or does anyone know of a workaround? I have a large code base that I am porting over/updating to be able to run on a new server and a bunch of queries are failing because of this issue
