### ISSUE TITLE
[Bug] temporary memory of job increases massive when using CLOB/JSON field in SQL-request

### ISSUE THREAD

**Issue by nedi-dev** [markdirish/node-odbc#283]
Describe the bug
While using "DB2 for i" nodes in Node-RED for a REST-API-application we discovered a massive usage of temporary memory of QP0ZSPWT-job.
It increases the value by 1 MB for 10 requests.
Analysis showed that the behaviour occurs in the idb-connector as well as in the odbc package.
Finally the usage of a clob-field in a sql view with DB2-JSON-aggregate functions is the root of the problem.
All other connection-properties can be neglected.

See further description here:
https://github.com/IBM/nodejs-idb-connector/issues/156

**Comment by nedi-dev** [comment]
Meanwhile there was a proposal for a workaround in the referenced thread.
In our project we casted the clob-fields in the SQL-statements to varchar.
This solved the issue but we are limited to a small number of characters.

Unfortunately I haven't got time to check the other workaround.

**Comment by kadler** [comment]
Since this issue occurs in both idb-connector and node-odbc, it is likely an issue in the database. For performance reasons, LOBs are left open up to a certain threshold so this could be using more memory in the server jobs though I don't know for sure (you'd have to talk to a database expert). See [QAQQINI](https://www.ibm.com/docs/en/i/7.5?topic=qaqqini-query-options) option LOB_LOCATOR_THRESHOLD for more info.

**Comment by nedi-dev** [comment]
Talked to Scott Forstie (IBM i, DB2 Expert) this week at 
Common-Conference in Germany. He experienced a similar situation and 
might have a solution for this. Maybe you can verify that?!?
