### ISSUE TITLE
 when  run node index.js return Segmentation fault (core dumped) every time.

### ISSUE THREAD

**Issue by ignoric** [markdirish/node-odbc#303]
hello I'm use  os ubuntu 18 , node.js 16 , unixodbc and connect to Tibero database.
I can connect to database tibero with isql Tibero6
<img width="580" alt="Screen Shot 2566-01-07 at 10 02 06" src="https://user-images.githubusercontent.com/43632026/211128550-622c5b2f-9976-4e7d-adc6-2b93ae83997b.png">

unixodbc version

<img width="570" alt="Screen Shot 2566-01-07 at 10 17 55" src="https://user-images.githubusercontent.com/43632026/211129049-1e0fb614-3cec-4414-aca3-da12f376d4bd.png">

I use npm I odbc 2.4.6 
#index.js
<img width="563" alt="Screen Shot 2566-01-07 at 10 10 04" src="https://user-images.githubusercontent.com/43632026/211128796-4aa26c5c-5a60-4f52-a385-b1bbf36ccb78.png">

and this results
<img width="561" alt="Screen Shot 2566-01-07 at 10 10 31" src="https://user-images.githubusercontent.com/43632026/211128819-eebe6ad1-47a6-4cc2-b5db-37575de57fbb.png">

I chang os ubuntu 20 to ubuntu 18, node 14 to node 16 but I same problem.
I don't know how to fix it please help me.

I expecting to can connect to unixodbc with node "odbc" 

thank you

**Comment by kadler** [comment]
Can you provide a backtrace?

run `gdb --args node index.js`

Then once gdb starts up, use command `r` to run, then wait for the segfault and run command `bt` to get the backtrace.

Also, it's preferable to copy/paste the output in code blocks instead of using screenshots. Screenshots are not searchable or selectable.
