### ISSUE TITLE
[BUG] Database error is not detected / returned

### ISSUE THREAD

**Issue by ErikJansenIRefact** [markdirish/node-odbc#324]
**Describe your system**
* `odbc` Package Version:
* ODBC Driver: SQLSERVER 18
* Database Name: SQLServer
* Database Version: 2019
* Database OS: Linux
* Node.js Version: 16.15.1
* Node.js OS: MacOS Ventura

**Describe the bug**
When a query is executed on the database and the database reports an error this error is not returned in the client.

**Expected behavior**

We expected that an error was returned and that we are able to catch the error and rollback the transaction.
SQLServer reports the following error (when trying to insert the 3rd record):

Msg 2627, Level 14, State 1, Line 5
Violation of PRIMARY KEY constraint 'PK__test__3BD019E59F3DB7B5'. Cannot insert duplicate key in object 'dbo.test'. The duplicate key value is (1).

This error is however not reported back to the odbc client!

**Code**
A table in the database exists:
CREATE TABLE IR_TSTGIN.dbo.TEST (x int primary key);

Next execute the following code (we are deliberately inserting a duplicate record):

```javascript
const odbc = require('odbc');

async function connectToDatabase() {
    const connectionConfig = {
        connectionString: 'DSN=MSSQL2019;uid=sa;pwd=iRefact2017',
        connectionTimeout: 10,
        loginTimeout: 10
    };

    const connection = await odbc.connect(connectionConfig);
    const SQL = `
    insert into IR_TSTGIN.dbo.test (x) values (1);
    insert into IR_TSTGIN.dbo.test (x) values (2);
    insert into IR_TSTGIN.dbo.test (x) values (1);
    `;
    await connection.beginTransaction();
    const result = await connection.query(SQL);
    await connection.commit();

}

connectToDatabase()
    .catch(error => {
        console.dir(error, {
            depth: null
        });
    });
```

**Comment by ErikJansenIRefact** [comment]
Please do not mark as stale. Would be nice if someone can take a look at the problem and report if this issue can be fixed or present workarounds.

**Comment by markdirish** [comment]
Hi @ErikJansenIRefact ,

I would think that an error would return a bad `SQLRETURN` value, which should then get information from the diagnostic records.[ If you follow these steps to turn on debugging](https://github.com/markdirish/node-odbc#debugging), then run your script above, then paste the output here, it should help greatly in determining the location of the issue.

**Comment by markdirish** [comment]
Believe it or not, this might be the expected behavior. In your log, the `SQLExecute` for the last query takes place here, and then `SQLRowCout` is called indicating 3 rows were affected:

```
[ODBC][79591][1683131957.479624][SQLExecute.c][187]
		Entry:
			Statement = 0x7f801d046400
[ODBC][79591][1683131957.480809][SQLExecute.c][357]
		Exit:[SQL_SUCCESS]
[ODBC][79591][1683131957.480866][SQLRowCount.c][173]
		Entry:
			Statement = 0x7f801d046400
			Row Count = 0x7f801cf1c530
[ODBC][79591][1683131957.480951][SQLRowCount.c][247]
		Exit:[SQL_SUCCESS]
			Row Count = 0x7f801cf1c530 -> 3 (64 bits)
```

So why does it return `SQL_SUCCESS`? Well, [the ODBC documentation](https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/errors-and-batches?view=sql-server-ver16) notes that, **depending on the driver implementation**, four different things can happen with a batch of SQL statements, including:

> All of the statements except the error statement are executed.

and that in such a case,

> [the ODBC functions] may return SQL_SUCCESS_WITH_INFO or SQL_SUCCESS, depending on the implementation.

It goes on to state that diagnostic information will be available in all of the four cases, but I _think_ they mean only in cases where `SQL_SUCCESS` isn't returned (so `SQL_SUCCESS_WITH_INFO` or `SQL ERROR`). If I am reading it correctly, its possible the driver implementation is simply to return this way. This `odbc` package certainly isn't doing anything too crazy with these queries, simply binding the parameters (it seems like you changed your query from the original issue and are passing parameters), and then calling `SQLExecute`.

We can do one final test to see if its driver behavior: Using `isql`, connect to the datasource and run your SQL statement from the original issue. See if it returns any error or diagnostic information.

```
isql -v MSSQL2019 (uid) (pwd)
SQL> (run your batch statement here)
```

**Comment by kadler** [comment]
The provided odbc.log doesn't look like it's executing the code from the issue description.

I see the following statements being executed:
- `create table dbo.test_parameters (id int, textValue varchar(100), numValue int);`
- `insert into dbo.test_parameters values (?, ?, ?);`
- `select * from dbo.test_parameters order by id`

**Comment by markdirish** [comment]
@kadler and I believe we have isolated the issue.

It may be a driver bug, but it seems that the SQL Server ODBC driver doesn't throw an error when making a batch execution where one of the statements fails when using the `SQLExecDirect` ODBC function to run the batch. When running with `SQLPrepare` and `SQLExecute`, like `isql` does, it does throw an error. Doesn't seem like this should be the behavior, but that's what happens.

Here are some solutions:

1. Send a bug report to Microsoft and tell them that this doesn't seem right, and hope the fix it (months to years turnaround)
2. Rewrite this package to always use `SQLPrepare` / `SQLExecute` workflow like isql does, with binding taking place only if parameters are passed (weeks to months turnaround)
3. Change the query to look like `insert into pktest (x) values (1), (2), (1)`, which does seem to fail with the current package (although the entire statement fails, and 0 entries are made in the table) (immediate turnaround)

The correct answer might be "all of the above", but for immediate relief you should probably try to see if option 3 works for you. Obviously it fails the entire batch, which isn't ideal. I will look into how much work doing prepare/execute would be.

**Comment by ErikJansenIRefact** [comment]
We have found a workaround. When sending a batch of statements you need to set SET NOCOUNT ON as the first statement.
