### ISSUE TITLE
Not returning results properly on windows

### ISSUE THREAD

**Issue by maxkisung** [markdirish/node-odbc#39]
connection.callProcedure() returns only the first char of each parameter 
and
statement.execute() returns the same parameters that were passed in.

I have not tested this on ibm yet because of my other issue  #38

**Comment by maxkisung** [comment]
I guess the statement.bind(parameters, callback?) is not meant to return output parameters
-[ "All parameters will be input parameters."](https://github.com/markdirish/node-odbc#parameters-16)

**Comment by markdirish** [comment]
Sorry, was actually working on this today and found some other bugs with callProcedure that I've had to fix.

You are correct, statement.execute() only binds SQL statements, which according the ODBC docs are only INPUT parameters.

Can you show me how you are trying to call `callProcedure`? I have tested it a lot today and had it returning `CHAR` and `VARCHAR` data exactly as I expected, not just the first character

**Comment by maxkisung** [comment]
let statement = await connection.createStatement();
        let sql = "CALL foo.bar(?,?,?,?,?,?,?,?,?)";
        await statement.prepare(sql);
        let output = [-1, -1, 487878, 1, 2, '20190919', 0, 0, 0];
        await statement.bind(output);
        var result = await statement.execute();


all paramaters are input/output

**Comment by markdirish** [comment]
Ok, I have recreated this with INOUT params, I can see that only the first character is being returned for some reason. I will investigate further, probably some little oversight

**Comment by markdirish** [comment]
Hi @maxkisung ,

I believe I have fixed the problem or INOUT parameters on `.callProcedure`. Can you install the package from my `issue39` GitHub branch to confirm that the issue is fixed for you?

To do this, run
```
$ npm install --save markdirish/node-odbc#issue39
```
I have some other issues I am working to fix as well, and then hopefully will soon get this all merged and available on npm as version 2.2.2.

Thanks!

**Comment by maxkisung** [comment]
i'm not sure but i think it's changing my input parameters to empty strings or null now.  is there a way to log what values are being passed to the driver?

**Comment by markdirish** [comment]
I have been testing this morning and haven't found any indication that input params are empty. For CHAR, VARCHAR, BIGINT, TIME, and TIMESTAMP fields, I am sending IN params and funneling them to OUT params, and seeing data as I would expect.

I have updated to add a DEBUG message to print out the strings that are boudn when you have 'DEBUG' defined. To activate it:

* Redownload the package from that GitHub
* In binding.gyp, around line 16, change the line `'NAPI_EXPERIMENTAL'` to `'NAPI_EXPERIMENTAL', 'DEBUG'`
* Rebuild with `node-gyp rebuild`

Now when you run your program, your terminal will get a lot of debug information. When it is calling BindParameters(), there should be lines that say:

```
The string value of the data sent is = <YOUR STRING VALUE>
```

From there you should be able to see what is exactly bound on the parameters

**Comment by gabheadz** [comment]
Still having same error in version 2.3.4 on linux and node 10.22, only first character of output parameters is returned.

![image](https://user-images.githubusercontent.com/15148117/90846562-07f94980-e32e-11ea-9988-715da04025b1.png)

Last 2 params should be 

![image](https://user-images.githubusercontent.com/15148117/90846777-8f46bd00-e32e-11ea-8c1f-971c04275ae7.png)

**Comment by markdirish** [comment]
@gabheadz is `UNICODE` defined in the `binding.gyp` file in the odbc package directory? I have run this on my own Linux machine, but I am not seeing the same issue.

**Comment by markdirish** [comment]
Ok, for some reason this escaped me, but a good place to start would be to defined `CCSID=1208`, either in your connection string or in your DSN. The API that the `odbc` package uses on Node.js can only create UTF8 or UTF16 strings, so you have to set that CCSID (which will set the client CCSID, so Node.js can convert correctly). I'm not convinced thats the issue, but it is a place to start.

**Comment by kadler** [comment]
@gabheadz FYI there's no reason to use the "IBM i Access ODBC Driver 64-bit" and it's recommended that you use the standard "IBM i Access ODBC Driver". The former will be going away in a future version.

@markdirish On any modern Linux you should always be running in a UTF-8 locale, though the driver does require that the application call `setlocale` to use it (since POSIX says that an application _always_ starts in the C locale). Did we figure out if Node does this? Otherwise, yes, setting CCSID=1208 can work around this problem. We should probably set this to the default in the driver for non-Windows systems.
