### ISSUE TITLE
Losing precision of decimal types

### ISSUE THREAD

**Issue by jram930** [markdirish/node-odbc#42]
If I execute a query where I cast a value to a decimal type with precision specified, like CAST something AS DECIMAL(18,2), it loses the specified precision and just casts it to DECIMAL (with no precision specified).

**Comment by irgijs** [comment]
I can confirm. Executing this query:

`select cast( '10.22'      as numeric(4,2)   )  numeric` 

results in this javascript value

`10.2`

**Comment by jram930** [comment]
Can this get fixed ASAP? This is causing some pretty serious issues for my team.

**Comment by mfournier91** [comment]
This is affecting me, as well.

**Comment by markdirish** [comment]
I can look into this tomorrow (on vacation currently), I'm not sure why it would default to ONE digit but I can dig through the code, hopefully an easy fix.

**Comment by jram930** [comment]
Thanks @markdirish, appreciate it . Would be awesome if there is an easy fix.

**Comment by markdirish** [comment]
At conferences abroad all week, but I have replicated it on my own driver and DBMS. I will continue to work on it as I have time

**Comment by markdirish** [comment]
Identified the issue.

When binding `SQL_REAL`, `SQL_DECIMAL`, and `SQL_NUMERIC`, it binds to a SQL_C_CHAR that is null terminated. So I added +1 to the column size. But unfortunately, I didn't account for space for the decimal point, so `select cast( '10.22' as numeric(4,2) ) numeric` was creating a buffer of size 5, when it should be 6 (4 numbers, 1 decimal, and 1 null-terminator).

I am going to run some tests and make sure that adding 1 doesn't break other code, and then push up 2.2.2 tonight or tomorrow to fix this issue.

**Comment by jram930** [comment]
Awesome. Thanks for the fast turn around. Once it's pushed we'll plan to upgrade.

**Comment by markdirish** [comment]
2.2.2 should now be available. Let me know if that fixes the issue you are seeing!

**Comment by jram930** [comment]
Our node server is running on centos 7 and we are querying Cloudera Impala. We were on node 8, but I upgraded us to node 11 to try to use 2.2.2 since it seemed like 2.2.2 wasn't supported by node 8.

**Comment by jram930** [comment]
Hi @markdirish, figure anything out with this one so far?

**Comment by markdirish** [comment]
@jram930 ,

Making this my current priority. Just wondering what the underlying datatype of the field you are trying to query is? I will try to run this on my RHEL machine against Cloudera Impala. What is the underlying data type that you are trying to cast as a decimal? It might help me narrow down the issue.

**Comment by Myriad-Dreamin** [comment]
there might be a wrong expression at https://github.com/markdirish/node-odbc/blob/7835d28f4b4db6928127f9d8a363f97a3cce10a3/src/odbc.cpp#L545
```cpp
if ((int64_t)double_val == int_val) { // might be `fabs(double_val - int_val) < 1e-6`?
        parameter->ValueType = SQL_C_SBIGINT;
        parameter->ParameterValuePtr = new int64_t(value.As<Napi::Number>().Int64Value());
      } else {
        parameter->ValueType = SQL_C_DOUBLE;
        parameter->ParameterValuePtr = new double(value.As<Napi::Number>().DoubleValue());
}
```
here `(int)1.1 == 1` will be always true, so then bug will also occurs when inserting an decimal
@markdirish

**Comment by jram930** [comment]
@markdirish Sorry I haven't checked back in here in a long time. This is still an issue for us and we're on the latest version. Affecting many of our users. What information do you need from me?

**Comment by markdirish** [comment]
I've redone some of the logic around type binding for 2.3.0-beta, could you download that version and see if it is still an issue? You should be able to run `npm install odbc@beta` to get that version.

Then I would go into the `odbc/binding.gyp` and change the `defines` to:
```
'defines' : [
        'NAPI_EXPERIMENTAL', 'DEBUG'
],
```

then rebuild the binary by going to the `node_modules/odbc` directory and running `npm install`. When you run a minimal query like you have above: `select cast('10.22' as decimal(4,2)) from mydb.mytable limit 1`, it will print out debug information that might be helpful in determining the problem.

**Comment by kadler** [comment]
If I understand the code @Myriad-Dreamin pointed out right, it's trying to check if there are any decimal places in the value:
```c
if ((int64_t)double_val == int_val) {
```
but that should be instead:

```c
if (floor(double_val) == double_val) {
```

Of course, I'm not sure why we're even trying to convert to an int64_t at all if the value in JS is a double, just leave it as a double and let the driver/database convert it for you.

**Comment by markdirish** [comment]
The issue is that the value comes in as a Napi::Number, and I don't know if it is an integer or a double. There is no Napi function for checking, so there are work-arounds to try and check. See https://github.com/nodejs/node-addon-api/issues/265.

So what I am trying to do in this code is determine what type of number is coming in so I can bind it with the right C type. [This table](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/converting-data-from-c-to-sql-data-types?view=sql-server-ver15) makes it look like I can just bind all numbers to `SQL_C_DOUBLE`, but I'm afraid about how it will do the conversions (memory to memory conversion, or actually try to parse out integers from double values by removing the decimal).

**Comment by jram930** [comment]
@markdirish no that didn't work for me. Now if I cast 1234.56789 as a decimal(38,2) I get 0. Am expecting it to be 1234.56

**Comment by jram930** [comment]
To reiterate the issue, using this library against an Impala database/table, I created a simple table that stores the value 1234.56789 in the field1 column.

If I query that directly with Cloudera provided tools (Hue), with the following query:
select cast(field1 as decimal(38,2)) from mydb.mytable
I get 1234.56, which is correct

If I query that with this library I get 1234, which is not correct

**Comment by worksofliam** [comment]
I believe this is also happening with binding parameters.

For example: `select width from items where width = ?`. I bind `20.5` in my app, but I get items where the width is `20`. (Db2 for i)

**Comment by kadler** [comment]
@worksofliam that confirms what @Myriad-Dreamin was saying

**Comment by kadler** [comment]
> The issue is that the value comes in as a Napi::Number, and I don't know if it is an integer or a double. There is no Napi function for checking, so there are work-arounds to try and check. See [nodejs/node-addon-api#265](https://github.com/nodejs/node-addon-api/issues/265).

I did not realize that V8 had support for non-double numbers. Either way from the linked thread, they were asking for *32-bit* integer support. Doubles can exactly store all integers up to 53 bits in size, so having a 32-bit int in a 64-bit double is fine. You only run in to problems with 64-bit ints, since while doubles can store values larger and smaller than what a 64-bit int can, any integer using more than 53 bits will have a loss of precision.

I don't know how you'd do a double -> integer conversion other than casting it, which will truncate the decimal digits if there are any.

**Comment by markdirish** [comment]
I think there are two similar but unrelated issues here:

---

1. The original issues that @jram930 posted is likely an issue with `CAST`ing and getting the data type right for the `SQLBindCol` column, so that `SQLFetch` returns the right data and the data is converted correctly to the JavaScript environment. I have tested this issue on Db2 for i again just now, and I get the correct output:

```
CREATE TABLE MIRISH.TEST2 (DOUBLEFIELD DOUBLE)
INSERT INTO MIRISH.TEST2 VALUES(1234.5678)
```
```
[ { DOUBLEFIELD: 1234.5678 },
  statement: 'SELECT * FROM MIRISH.TEST2',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: 'DOUBLEFIELD', dataType: 8 } ] ]
```
```
[ { '00001': 1234.56 },
  statement: 'SELECT CAST(DOUBLEFIELD AS DECIMAL(38,2)) FROM MIRISH.TEST2',
  parameters: undefined,
  return: undefined,
  count: -1,
  columns: [ { name: '00001', dataType: 3 } ] ]
```

My DEBUG information also looks correct, primarily that `SQLDescribeCol` says the field is `DataType = 3` (`SQL_DECIMAL`) `ColumnSize = 38, DecimalDigits = 2`
```
[SQLHENV: 0x3c5d230][SQLHDBC: 0x7f57080008c0][SQLHSTMT: 0x7f57000008c0] ODBCConnection::BindColumns()
[SQLHENV: 0x3c5d230][SQLHDBC: 0x7f57080008c0][SQLHSTMT: 0x7f57000008c0] ODBCConnection::BindColumns(): Running SQLNumResultCols(StatementHandle = 0x7f57000008c0, ColumnCount = 0
[SQLHENV: 0x3c5d230][SQLHDBC: 0x7f57080008c0][SQLHSTMT: 0x7f57000008c0] ODBCConnection::BindColumns(): SQLNumResultCols passed: ColumnCount = 1
[SQLHENV: 0x3c5d230][SQLHDBC: 0x7f57080008c0][SQLHSTMT: 0x7f57000008c0] ODBCConnection::BindColumns(): Running SQLDescribeCol(StatementHandle = 0x7f57000008c0, ColumnNumber = 1, ColumnName = , BufferLength = 128, NameLength = 0, DataType = 0, ColumnSize = 0, DecimalDigits = 0, Nullable = 0)
[SQLHENV: 0x3c5d230][SQLHDBC: 0x7f57080008c0][SQLHSTMT: 0x7f57000008c0] ODBCConnection::BindColumns(): SQLDescribeCol passed: ColumnName = 00001, NameLength = 5, DataType = 3, ColumnSize = 38, DecimalDigits = 2, Nullable = 1
```

@jram930 , I have two questions: 
1. Does your other connector also use an ODBC driver, or does it connect to the database through a different way? If it is not an ODBC driver, it might be a bug in the Impala Cloudera driver, since it seems to work as expected on my DBMS with my driver.
2. Can you post (or email me at mirish@ibm.com) the debug information from running the query? That would help me determine what is happening on an ODBC level to cause the issue.

---

2. The second issue that @Myriad-Dreamin and @worksofliam are talking about has to do with binding parameters, particularly when using `query`. When using `query`, bind values are stored as their best guess data type, as all JavaScript values have to be stored in C types before I can call `SQLDescribeCol`. This is contrasted with the prepare-bind-execute workflow, where I call `SQLDescribeCol` after prepare but before bind, so I know exactly what the values should be bound to.

This issue I am able to replicate, and I am looking through @Myriad-Dreamin  and @kadler 's suggestions to see if they fix the issue.

**Comment by jram930** [comment]
@markdirish I went to Cloudera's website and found an updated version of their odbc connector. When I upgraded that to the latest version this bug no longer exists for us on version 2.2.2! Thanks for the idea that the problem might lie there. Thanks for looking into it, appreciate it.
