### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by snotmare** [markdirish/node-odbc#56]
Please add a @types/odbc package to provide typescript support.

**Comment by markdirish** [comment]
Is this how packages still provide information about function signatures to TypeScript? I thought that the new way was to create a `.d.ts` file that has definitions inside of it?

Willing to work on this though, seems like a good enhancement!

**Comment by snotmare** [comment]
Hello Mark! Yes, either way would be great. I believe you are correct that having the types inside the odbc package would be the better way to go. However, you could go with a new @types/odbc package in npm if you didn't want to modify the existing package.

We've built our entire code base in typescript and love it. It may not be too hard to convert your code to ts. https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by markdirish** [comment]
@snotmare Would you mind downloading the branch `typescript-.d.ts` and see if it does what you want it to? 
```
npm install markdirish/node-odbc#typescript-.d.ts
```
I made a simple odbc TypeScript application and it seemed to give me good suggestions (although functions have multiple definitions so that can be a little much when trying to fill). But it gave me red underlines when using the wrong types and what not.

**Comment by snotmare** [comment]
@markdirish Those typings worked for me. It's nice being able to use this with code assist. Can't wait for it to be released!

There may be some cases where it makes sense to use unknown instead of any. It does about the same thing, but allows type checking to continue.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

**Comment by markdirish** [comment]
Hi @snotmare , I updated the branch again. Instead of returning `Array<any>` for results, I extended the Array class and added the properties that exist on results returned from the package. I also extended the `Error` object to add the Array of ODBCErrors that exists on it (giving native message, code, and state).

Could you download the latest code from the branch and see if it all works well, hopefully even better than before?

**Comment by snotmare** [comment]
I think that looks pretty good. I created a PR for you to review as a suggestion. It's my first PR ever, so hopefully I did it right!
