### ISSUE TITLE
Create pre-built binaries for commonly used systems

### ISSUE THREAD

**Issue by markdirish** [markdirish/node-odbc#65]
Currently, `odbc` will install from the source files when downloaded from NPM. This is prone to breaking and requires special flags/definitions on each system, and often requires users to have special software installed (e.g. Visual Studio compilers on Windows) (see #34, #59).

Instead, should use a system like (`node-pre-gyp`)[https://www.npmjs.com/package/node-pre-gyp] to download and install pre-built binaries for commonly used systems, and only fallback to local compilation when there is no binary for a system. 

Systems to support should include:

- [x] Windows (x86)
- [ ] Windows (ARM)
- [x] MacOS
- [x] Linux (x86)
- [ ] Linux (POWER)
- [x] IBM i

**Comment by markdirish** [comment]
Going to close, we have prebuilt binaries for many of the most used systems. Having prebuilt binaries for MacOS ARM and Windows ARM would still be great, but there are extant issues in node-pre-gyp and node-gyp that prevent defining a target architecture.

**Comment by MiniMarker** [comment]
Hi @markdirish. 
As of today Apple is no longer selling any x64 MacBooks. Is it possible to revisit this issue and include an arm64 built. I would think this would be very beneficial for the future for this library. 

Some of my team members are having issues with installing this dependency since npm for some reason is trying to download a `odbc-v2.4.8-darwin-arm64-napi-v5.tar` binary that doesn't exist. But others (everyone uses m1 pro) have no problems installing this package.

I'm not very familiar with the build and package stages of this type of applications, so I dont have much knowledge to contribute.

Best regards!

**Comment by MatthewReed303** [comment]
Hi @markdirish and @MiniMarker I'm having same issue using an RPI with arm64. Node is looking for odbc-v2.4.8-darwin-arm64-napi-v6.tar but it does not exist.

`314.3 node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.8/odbc-v2.4.8-linux-arm64-napi-v6.tar.gz`

Can you please do a release for arm
