### ISSUE TITLE
Numbers are being inconsistently returned

### ISSUE THREAD

**Issue by bennyt2** [markdirish/node-odbc#96]
**Describe your system**
* `odbc` Package Version: 2.3.0
* ODBC Driver: Microsoft Access Driver (*.mdb, *.accdb)
* Database Name: Microsoft Access
* Database Version: 2002-2003
* Database OS: Windows 10
* Node.js Version: 12.18.0
* Node.js OS: Windows 10

**Describe the bug**
Numbers are being inconsistently returned from Access database. For example, 0 is sometimes returned as 0.04. In the Access database, it's 0.

**Expected behavior**
Data should consistently be returned. I did not have this problem in version 1.4.6.

**To Reproduce**
### Add an ODBC x64 Microsoft Access datasource called "odbc-number-issue"

Driver: https://www.microsoft.com/en-us/download/details.aspx?id=13255

### Checkout and build the example repo

This repo contains the Access database and examples of how the query returns inconsistent data.

Repo: https://github.com/bennyt2/odbc-number-issue

`npm install`
`npm run build`
`npm start`

Running the program will attempt to execute the offending query 100 times. I usually get between 0-5 hits from this, but I've seen over 200 in a single run. It's random. It may take a couple runs to see a console log that looks like this:

`Event_no 128 should have Event_dist 1500, but Event_dist is 1500.02`

In this example, if you look at Event_no 128 in the Event table, you will see Event_dist is `1500`.

I'm sure this is some kind of minor data type issue, but the inconsistency is causing problems.

**Additional context**

* I know this DB format is very old, but I don't have the option of upgrading.
* I was not able to get the DEBUG output working in binding.gyp. I followed these steps but saw nothing in my terminal:
** Change line 16 from `'NAPI_EXPERIMENTAL'` to `'NAPI_EXPERIMENTAL', 'DEBUG`
** `cd node_modules/odbc && npm install`
** `cd ../../ && npm run r`

**Comment by groupespc69** [comment]
I have a similar problem with a 4D software database. 
It seems to happen randomly on float numbers, specially those with no decimal part.
Some trailing random digits (1 to 4) are added to the number, leading to increase the number by 10 to 10000.
It doesn't appear on same records each time I execute the query.

Is this a problem of memory flush ?

**Comment by nedi-dev** [comment]
Urgent!
We see the same problem on IBM i with different data-tables. 
It is very urgent for us as we provide price-data to the online-shop.
These price-data is partly corrupted due to randomly added digits and missing decimal symbols.

Describe your system

    odbc Package Version: 2.3.1
    ODBC Driver: IBM i
    Database Name: DB2 for i / IBM i
    Database Version: 7.3
    Database OS: OS/i 7.3
    Node.js Version: 12.14.0
    Node.js OS: OS/i 7.3

The error can be reproduced when you execute the same simple "SELECT ... FROM ..." statement multiple times in a row.
After a few correct cycles the count of errors increases with every increment. Although the records with errors are not allways the same.
We have multiple examples with NUMERIC 6,0 (returning 7 digits!) or NUMERIC 7,2 (returning 3 decimal digits or missing the decimal dot!) datafields.
If needed, we can provide logs of our findings.

A quick review to this issue is highly appreciated.

**Comment by markdirish** [comment]
This will be my top priority today.

**Comment by nedi-dev** [comment]
Thank you ... looking foreward to your results.

**Comment by groupespc69** [comment]
Good news, thanks.

**Comment by markdirish** [comment]
Turns out, there's all _sorts_ of gibberish being returned when numbers are bound to C character target types (like `NUMERIC`):
```
stored char data is is 123�v� 
stored char data is is 123.00>`
stored char data is is 123.0000
```
Since these are converted to numbers using `atof()` before being sent to JavaScript, the gibberish is just ignored. Only when it happens that a number is in that giberish is there an issue, where `atof()` includes it in the number it returns. 

Should be fairly easy to track down.

**Comment by markdirish** [comment]
Ok, does anyone want to try out the new version and let me know if it works? Isn't on npm, just on my github so far:

`npm install markdirish/node-odbc#issue96-inconsistent-numbers`

**Comment by nedi-dev** [comment]
Perfect, will try tomorrow morning (about 10 hours from now).

**Comment by nedi-dev** [comment]
Had some trouble with installing using your install command because of using password for ssh public key.
Following command worked for me:
> npm install git+ssh://git@github.com:markdirish/node-odbc#issue96-inconsistent-numbers

My tests work fine now.
I'll ask my colleague to test it with his examples.
Getting back shortly with the results.

**Comment by nedi-dev** [comment]
Seems to be fine as well.
As the fix is urgent for us, what do you suggest for taking this corrections into production?
Should we take this branch or better waiting for a 2.3.2 version?

**Comment by markdirish** [comment]
Better waiting for 2.3.2. I will try to push it out today!

**Comment by nedi-dev** [comment]
Great! Thanks a lot for your qualified short term support.

**Comment by groupespc69** [comment]
Great news. Thanks for this correction and your support.

**Comment by markdirish** [comment]
Should now be live in 2.3.2!

**Comment by nedi-dev** [comment]
Works in 2.3.2
